on:
 push:
   branches:
     - master
  



jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: "github actions"
        run: ls 

      - uses: actions/checkout@v3

      - name: "docker login"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: "build and push"  
        run: docker build -t ${{ secrets.DOCKER_NAME }}/myimage:latest . && docker push ${{ secrets.DOCKER_NAME }}/myimage:latest 

